name: CI tests

on: [push, pull_request]

jobs:

  ci_tests:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch